name: Test nimproto3

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # so that problems in nim devel don't stop other tests
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        nim-version:
          - '2.2.x'
          - stable
          - devel
        exclude:
          # setup-nim-action doesn't support this
          - os: windows-latest
            nim-version: devel
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v4
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ matrix.nim-version}}-${{ hashFiles('yaml.nimble') }}
        restore-keys: |
          ${{ runner.os }}-nimble-${{ matrix.nim-version}}-
    - name: Setup nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ github.token }}

    - name: Install Packages
      run: nimble install -y
    
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      
    - name: Test
      run: |
        nimble test
